### PR TITLE
Refactored for compatibility with Bokeh 3.2.0

### LINKED ISSUE #6: callback_analysis.ipynb fails to run with latest version of bokeh
Using Bokeh 3.2.0 and python 3.10 on Ubuntu 22.04, the following error is seen in cell 6:

    AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width

Similar errors are given for plot_height. And DatetimeTickFormatter objects no longer accept lists of formatting strings as of Bokeh 3.0

### PR DESCRIPTION
**Pull request by nightduck**
Fixes #6

### CODE REVIEW

**Comment by nightduck** [comment]
Confirmed working on Ubuntu 22.04, with python 3.10, and Boken 3.2.0

**Review by christophebedard — APPROVED** [review]
Works for me, thanks for the fix!

Could you just sign-off your commit?

**Comment by nightduck** [comment]
I don't know how to signoff a commit that's already been pushed without doing a force push to overwrite it, which I assume would screw up this PR

**Comment by christophebedard** [comment]
It wouldn't screw the PR. I do it all the time :stuck_out_tongue:

**Review by christophebedard — APPROVED** [review]
Thanks again for the fix and for amending your commit!

**Pull request merged**
